apiVersion: v1
kind: Namespace
metadata:
  name: ns1
  labels:
    name: ns1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap1
data:
  KEY1: value1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-ns1
  namespace: ns1
data:
  KEYNS1: valuens1
---
apiVersion: v1
kind: Secret
metadata:
  name: secret1
data:
  SECRET1: dmFsdWUtMg0KDQo=
---
apiVersion: v1
kind: Secret
metadata:
  name: secret1-ns1
  namespace: ns1
data:
  SECRETNS1: eW8K